# Generated by Django 5.0.4 on 2024-05-12 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_blog_preview"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="slug",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="slug"
            ),
        ),
    ]
