# Generated by Django 4.2.2 on 2024-05-24 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_alter_product_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["category"],
                "permissions": [
                    ("can_edit_publication_sign", "Can edit publication sign"),
                    ("can_edit_description", "Can edit description"),
                    ("cand_change_category", "Cand change category"),
                ],
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
    ]
